import { Suspense, useEffect, useMemo } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";

import { useControls } from "leva";
import { Canvas } from "@react-three/fiber";

import Box from "@/components/Box";
import Floor from "@/components/Floor";
import LightBulb from "@/components/LightBulb";
import Controls from "@/components/Controls";
import LoadModel from "@/components/LoadModel";
import { useAtom, useAtomValue } from "jotai";
import { targetAtom, transformModeAtom } from "@/atoms/controls";
import LevaGlobalInterface from "@/components/LevaGlobalInterface";
import { House } from "@/components/Meshs/House";

import {
  Selection,
  Outline,
  EffectComposer,
} from "@react-three/postprocessing";
import { Select, Sky } from "@react-three/drei";
import { Model } from "@/components/Meshs/Model";

export default function Home() {
  const [target, setTarget] = useAtom(targetAtom);
  const transformMode = useAtomValue(transformModeAtom);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.scene}>
        <Canvas
          shadows
          className={styles.canvas}
          camera={{
            position: [-6, 7, 7],
          }}
          onPointerMissed={(e: MouseEvent) =>
            e.type === "click" && setTarget({ name: null })
          }
        >
          <Sky
            distance={1000}
            inclination={0.6}
            azimuth={0.3}
            sunPosition={[4, 2, 2]}
          />
          <LevaGlobalInterface />

          <ambientLight color={"white"} intensity={0.2} />
          <LightBulb position={[0, 3, 0]} />

          <Select>
            {/* <EffectComposer multisampling={8} autoClear={false}>
              <Outline
                blur
                visibleEdgeColor="white"
                edgeStrength={100}
                width={700}
                height={700}
              />
            </EffectComposer> */}
            <Model />
            <Box nameProp="box1" position={[2, 2, 0]} />
            <Box nameProp="box2" />
          </Select>

          <Controls />
        </Canvas>
      </div>
    </>
  );
}
